### ISSUE TITLE
Update guzzle version

### ISSUE THREAD

**Issue by jcnventura** [platformsh/platformsh-client-php#9]
Would it be possible to update guzzlehttp/guzzle to ~6.1 ?

Drupal console also depends on guzzle, and it requires that version.

**Comment by pjcdawkins** [comment]
Hi @jcnventura 

If you're asking because of dependency conflicts between the [CLI](/platformsh/platformsh-cli) and Drupal Console, I'd recommend you switch to the Phar install of the CLI, instead of using Composer. And you can also install Drupal Console via a Phar. Then it doesn't matter about the difference in dependencies.

CLI: `curl -sS https://platform.sh/cli/installer | php`
Drupal Console: `curl -LSs http://drupalconsole.com/installer | php`

There are two problems with Guzzle 6:

1. it requires PHP 5.5 (the Platform.sh CLI supports PHP 5.4, so requiring 5.5 would be a breaking change)
2. we would have to update or replace our OAuth2 plugin (https://github.com/commerceguys/guzzle-oauth2-plugin).

**Comment by jcnventura** [comment]
OK. Thanks. I've moved to platform using phar, and today it self-updated :) Neat..
